config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  # 特定のコントローラーがどこに存在するかを指定する
  devise_for :admin, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]
    resources :posts, only: [:index, :show, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # 特定のコントローラーがどこに存在するかを指定する
  # skip オプションで不要なルーティングを削除
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }

  # get '/users' => redirect("/users/sign_up")
  resources :users, only: [:index, :show, :edit, :update] do
    resources :post_comments, only: [:index] do
      member do
        delete 'destroy_from_index'
      end
    end
    resources :favorites, only: [:index]
  end
  get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  patch 'withdraw' => 'users#withdraw', as: 'withdraw'

  resources :posts, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'runking'
    end
    member do
      delete 'destroy_from_user_show'
    end
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm', to: 'contacts#confirm'
      get 'confirm', to: 'contacts#new'
      post 'back', to: 'contacts#back'
      get 'back', to: 'contacts#new'
      get 'complete', to: 'contacts#complete'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  
  # is_deletedがfalseの時に認証する
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :name, presence: true, length: {maximum: 20 }
  
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @q = User.ransack(params[:q])
    @users = @q.result.page(params[:page]).reverse_order
  end
  
  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "更新しました。"
      redirect_to admin_user_path(@user)
    else
      flash[:alert] = "更新が失敗しました。"
      redirect_to admin_user_path(@user)
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = "削除しました。"
      redirect_to admin_users_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :is_deleted)
  end
  
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  before_action :user_state, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected
  
  # 退会しているかどうか
  def user_state
    # 入力されたemailからアカウントを探す
    @user = User.find_by(email: params[:user][:email])
    # アカウントを取得できなかった場合、このメソッドを終了する
    return if !@user
    # valid_password? → 特定のアカウントのパスワードと入力されたパスワードが一致しているかを確認するためのDevise が用意しているメソッド
    if @user.valid_password?(params[:user][:password]) && @user.is_deleted == true
      redirect_to new_user_registration_path
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # deviseのヘルパーメソッド
  before_action :authenticate_user!,except: [:index, :show]

  def index
    redirect_to new_user_registration_path
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render 'edit'
    else
      redirect_to user_path(@user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      redirect_to edit_user_path(@user), flash: { error: @user.errors.full_messages }
    end
  end

  # 退会確認画面
  def unsubscribe
    @user = current_user
  end

  # 退会
  def withdraw
    @user = current_user
    if @user.update(is_deleted: true)
      reset_session
      redirect_to root_path
      flash[:withdraw] = "退会しました"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/admin/users_helper.rb
module Admin::UsersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<!--<div class="text-right"><%#= link_to "退会する", unsubscribe_path(@user), class: "btn btn-danger" %></div>-->

<div class="edit_user">
  <div class="text">
    <h2>ユーザー名変更</h2>
    <%= form_with model:@user, local:true do |f| %>
      <% if flash[:error].present? %>
        <div class="error_messages">
          <% flash[:error].each do |e| %>
            <li><%= e %>
          <% end %>
        </div>
      <% end %>
      <p class="space"><h5>ユーザー名</h5></p>
      <div class="space"><%= f.text_field :name, autofocus: true, placeholder:"ニックネーム" %></div>
      <div class="space"><%= f.submit "変更を保存" %></div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user_show">
  <div class="user_name">
    ユーザー名
    <% if user_signed_in? && @user.id == current_user.id %>
      <h4><%= @user.name %></h4>
    <% else %>
      <h4><%= @user.name %><span class="small">さん</span></h4>
    <% end %>
  </div>
  <div class=”container”>
    <div class="row-fluid">
      <div class="col-3, link">
      <% if user_signed_in? && @user.id == current_user.id %>
        <p><%= link_to "ユーザー名変更", edit_user_path(@user) %></p>
        <p><%= link_to "コメント履歴",  user_post_comments_path(@user) %></p>
        <p><%= link_to "お気に入り履歴",  user_favorites_path(@user) %></p>
        <%= form_with model:@user, local:true do |f| %>
          <p><%= link_to "退会", unsubscribe_path(@user) %></p>
        <% end %>
      <% end %>
    </div>

    <div class="col-9, user_posts">
      <h5>投稿一覧履歴</h5>
      <% @posts.each do |post| %>
      <table class=”row”>
        <td class="col-md-3"><%= attachment_image_tag post, :image,size:"150x100", fallback:"no_image_square.jpg" %></td>
        <!--asset_path(no_image_square.jpg)-->
        <td class="col-md-9">
          投稿日時：<%= post.created_at.strftime('%Y/%m/%d') %><br>
          住所 / 地名 / 駅名：<%= post.address %><br>
          投稿文：<%= post.writings.truncate(30) %><br>
          <%= link_to "詳細",  post_path(post.id) %>
          <% if user_signed_in? &&  post.user.id == current_user.id %>
            <%#= link_to "編集", edit_post_path(@post) %>
            / <%= link_to "削除", destroy_from_user_show_post_path(post), method: :delete %>
          <% end %>
        </td>
      </table>
      <% end %>
    </div>
  </div>
</div>

<%= paginate @posts %>

app/views/users/unsubscribe.html.erb
<div class="unsubscribe">
  <div class="text">
    <h2>本当に退会しますか？</h2>
    <p>
      退会すると、会員登録情報や<br>
      これまでの履歴が閲覧できなくなります。<br>
      退会する場合は、「退会する」をクリックしてください。
    </p>
    <div class="btns">
      <%= link_to "退会する", withdraw_path(@user), method: :patch, class: "btn btn-outline-danger btn-sm" %>
      <%= link_to "退会しない", user_path(@user), class: "btn btn-outline-primary btn-sm" %>
    </div>
  </div>
</div>