config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  # 特定のコントローラーがどこに存在するかを指定する
  devise_for :admin, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]
    resources :posts, only: [:index, :show, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # 特定のコントローラーがどこに存在するかを指定する
  # skip オプションで不要なルーティングを削除
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }

  # get '/users' => redirect("/users/sign_up")
  resources :users, only: [:index, :show, :edit, :update] do
    resources :post_comments, only: [:index] do
      member do
        delete 'destroy_from_index'
      end
    end
    resources :favorites, only: [:index]
  end
  get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  patch 'withdraw' => 'users#withdraw', as: 'withdraw'

  resources :posts, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'runking'
    end
    member do
      delete 'destroy_from_user_show'
    end
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm', to: 'contacts#confirm'
      get 'confirm', to: 'contacts#new'
      post 'back', to: 'contacts#back'
      get 'back', to: 'contacts#new'
      get 'complete', to: 'contacts#complete'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
  
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true

  enum subject: { users: 0, posts: 1, post_comments: 3, others: 4 }
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end
  
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render 'new'
    end
  end
  
  def back
    @contact = Contact.new(contact_params)
    render 'new'
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver
      # ContactMailer.send_mail(@contact).deliver_now
      redirect_to complete_contacts_path
    else
      render 'new'
    end
  end
  
  def complete
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :subject, :message)
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/complete.html.erb
<div class='contacts_complete'>
  <h2>送信しました</h2>
</div>

app/views/contacts/confirm.html.erb
<div class="confirm_contact">
  <h4>お問い合わせ内容確認</h4>
  <table class="table table-hover">
    <tr>
      <th width="15%">お名前</th>
      <td width="85%"><%= @contact.name %></td>
    </tr>
    <tr>
      <th>メールアドレス</th>
      <td><%= @contact.email %></td>
    </tr>
    <tr>
      <th>要件</th>
      <td><%= @contact.subject_i18n %></td>
    </tr>
    <tr>
      <th>メッセージ</th>
      <td><%= @contact.message %></td>
    </tr>
  </table>
  <table width="100%">
    <tr>
      <td width="25%"></td>
      <td width="20%">
        <%= form_with model: @contact, url: back_contacts_path, local: true do |f| %>
          <%= f.hidden_field :name %>
          <%= f.hidden_field :email %>
          <%= f.hidden_field :subject_i18n %>
          <%= f.hidden_field :message %>
          <%= f.submit '入力画面に戻る' %>
        <% end %>
      </td>
      <td width="15%">
        <%= form_with model: @contact, url: contacts_path, local: true do |f| %>
          <%= f.hidden_field :name %>
          <%= f.hidden_field :email %>
          <%= f.hidden_field :subject_i18n %>
          <%= f.hidden_field :message %>
          <%= f.submit '送信' %>
        <% end %>
      </td>
      <td width="40%"></td>
    </tr>
  </table>
</div>

app/views/contacts/new.html.erb
<div class="new_contact">
  <h4>お問い合わせ</h4>
  <%= form_with model: @contact, url: confirm_contacts_path, local: true do |f| %>
    <%= render 'layouts/error_messages', model: f.object %>
    <div class="form-group">
      <%= f.label :name, 'お名前' %>
      <%= f.text_field :name, autofocus: true, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :email, 'メールアドレス' %>
      <%= f.text_field :email, autofocus: true, class: 'form-control' %>
    </div>
  
    <div class="form-group">
      <%= f.label :subject, '要件' %><br>
      <%= f.select :subject, Contact.subjects_i18n.invert,{} %>
    </div>

    <div class="form-group">
      <%= f.label :message, 'メッセージ' %>
      <%= f.text_area :message, size: '10x10', class: 'form-control' %>
    </div>

    <div class="new_contact_btn text-right">
      <%= f.submit '入力内容確認' %>
    </div>
  <% end %>
</div>