config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  # 特定のコントローラーがどこに存在するかを指定する
  devise_for :admin, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]
    resources :posts, only: [:index, :show, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # 特定のコントローラーがどこに存在するかを指定する
  # skip オプションで不要なルーティングを削除
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }

  # get '/users' => redirect("/users/sign_up")
  resources :users, only: [:index, :show, :edit, :update] do
    resources :post_comments, only: [:index] do
      member do
        delete 'destroy_from_index'
      end
    end
    resources :favorites, only: [:index]
  end
  get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  patch 'withdraw' => 'users#withdraw', as: 'withdraw'

  resources :posts, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'runking'
    end
    member do
      delete 'destroy_from_user_show'
    end
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm', to: 'contacts#confirm'
      get 'confirm', to: 'contacts#new'
      post 'back', to: 'contacts#back'
      get 'back', to: 'contacts#new'
      get 'complete', to: 'contacts#complete'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  # optional: true → nilを許可
  belongs_to :user, optional: true
  belongs_to :post
  
  validates :comment, presence: true, length: {maximum: 200 }

end

app/controllers/admin/post_comments_controller.rb
class Admin::PostCommentsController < ApplicationController
  before_action :authenticate_admin!
  
  def index
    @q = PostComment.ransack(params[:q])
    @post_comments = @q.result.page(params[:page]).reverse_order
  end
  
  def destroy
    @post_comment = PostComment.find_by(id: params[:id])
    if @post_comment.destroy
      flash[:destroy] = "削除しました。"
      redirect_to request.referer
    end
  end

end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  # deviseのヘルパーメソッド
  before_action :authenticate_user!,except: [:create]
  
  # 非同期通信
  def create
    @post = Post.find(params[:post_id])
    @post_comments = @post.post_comments
    if user_signed_in?
      # ログインしているユーザーidを紐づける
      @post_comment = current_user.post_comments.new(post_comment_params)
      @post_comment.post_id = @post.id
    else
      # ユーザーidはない
      @post_comment = PostComment.new(post_comment_params)
      @post_comment.post_id = @post.id
    end
    if @post_comment.save
      # flash[:create_comment] = "コメントしました"
    else
      redirect_to post_path(@post), flash: { error: @post_comment.errors.full_messages }
    end
  end
  
  # 非同期通信
  def destroy
    @post_comment = PostComment.find_by(id: params[:id])
    @post = @post_comment.post
    @post_comments = @post.post_comments
    @post_comment.destroy
  end

  def index
    @post_comments = PostComment.where(user_id: current_user.id).page(params[:page]).reverse_order
  end
  
  def destroy_from_index
    @post_comment = PostComment.find_by(id: params[:id])
    @post_comment.destroy
    redirect_to user_post_comments_path(current_user)
  end

  private

  def post_comment_params
    params.require(:post_comment).permit(:comment, :user_id)
  end

end

app/helpers/admin/post_comments_helper.rb
module Admin::PostCommentsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/views/admin/post_comments/index.html.erb
<div class="admin_post_comments">
  <div class="search">
    <%= search_form_for @q, url: admin_post_comments_path do |f| %>
    <div class="row">
      <div class="col-8"></div>
      <%#= f.label :address_or_writings_or_user_name_cont, "Keyword" %>
      <div class="col-3"><%= f.search_field :comment_or_user_name_cont, class: 'form-control', placeholder: '検索ワード', required: true %></div>
      <div class="col-1"><%= f.submit '検索', class: 'btn btn-primary' %></div>
    </div>
    <% end %>
  </div>
  <div class="container">
    <h4>コメント一覧</h4>
    <div class="notice"><%= flash[:destroy] %></div>
    <% @post_comments.each do |post_comment| %>
    <table class="row-fluid">
      <td class="col-5">
        <p><%= post_comment.created_at.strftime('%Y/%m/%d') %></p>
        <p>コメント文：<%= post_comment.comment %></p>
        <p>ユーザー：<%= user_name(post_comment.user) %></p>
        <p><%= link_to "削除", admin_post_comment_path(post_comment), method: :delete %></p>
      </td>
      <td class="col-7">
        <table ="row">
          <td class="col-10">
            <p><%= post_comment.post.created_at.strftime('%Y/%m/%d') %></p>
            <p>住所 / 地名 / 駅名：<%= post_comment.post.prefecture %> <%= post_comment.post.place %><br>
            <p>投稿文：<%= post_comment.post.writings.truncate(10) %></p>
            <p>ユーザー：<%= user_name(post_comment.post.user) %></p>
            <div class="tag-box">
              <% post_comment.post.tags.each do |tag| %>
                <span class="label"><%= tag.name %></span>
              <% end %>
            </div>
          </td>
          <td class="col-2">
            <p><%= link_to "詳細",  admin_post_path(post_comment.post.id) %></p>
          </td>
        </table>
      </td>
    </table>
    <% end %>
  </div>
</div>