config/routes.rb
Rails.application.routes.draw do

  root 'homes#top'

  # 特定のコントローラーがどこに存在するかを指定する
  devise_for :admin, skip: [:passwords, :registrations], controllers: {
    sessions: "admin/sessions"
  }

  namespace :admin do
    resources :users, only: [:index, :show, :update, :destroy]
    resources :posts, only: [:index, :show, :update, :destroy]
    resources :post_comments, only: [:index, :destroy]
  end

  # 特定のコントローラーがどこに存在するかを指定する
  # skip オプションで不要なルーティングを削除
  devise_for :users, skip: [:passwords], controllers: {
    registrations: "users/registrations",
    sessions: 'users/sessions'
  }

  # get '/users' => redirect("/users/sign_up")
  resources :users, only: [:index, :show, :edit, :update] do
    resources :post_comments, only: [:index] do
      member do
        delete 'destroy_from_index'
      end
    end
    resources :favorites, only: [:index]
  end
  get 'unsubscribe' => 'users#unsubscribe', as: 'unsubscribe'
  patch 'withdraw' => 'users#withdraw', as: 'withdraw'

  resources :posts, only: [:index, :new, :create, :show, :destroy] do
    collection do
      get 'runking'
    end
    member do
      delete 'destroy_from_user_show'
    end
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :contacts, only: [:new, :create] do
    collection do
      post 'confirm', to: 'contacts#confirm'
      get 'confirm', to: 'contacts#new'
      post 'back', to: 'contacts#back'
      get 'back', to: 'contacts#new'
      get 'complete', to: 'contacts#complete'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  
  validates :name, presence: true
  validates :email, presence: true
  validates :message, presence: true

  enum subject: { users: 0, posts: 1, post_comments: 3, others: 4 }
  
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  
  belongs_to :user
  belongs_to :post
  
  # post_idにuser_idが重複していないこと
  validates_uniqueness_of :post_id, scope: :user_id
end

app/models/home.rb
class Home < ApplicationRecord

  # 画像アップ用のメソッド（attachment）を追加してフィールド名に（image）を指定、refile使用時のルール
  attachment :image

end

app/models/post.rb
class Post < ApplicationRecord

  # 画像アップ用のメソッド（attachment）を追加してフィールド名に（image）を指定、refile使用時のルール
  attachment :image

  # optional: true → nilを許可
  belongs_to :user, optional: true
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :tags, dependent: :destroy

  validates :image, presence: true
  validates :prefecture, presence: true
  validates :place, presence: true
  validates :writings, presence: true, length: {maximum: 500 }

  # 引数で渡されたユーザidがFavoritesテーブル内に存在（exists?）するかどうかを調べる
  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
  
  def create_tags
    # 投稿した画像をAPI側に渡す
    tag_names = Vision.get_image_data(image)
    # API側から返ってきた値をもとにタグを作成する
    tag_names.each { |tag_name| tags.create(name: tag_name) }
  end

  # addressにprefecture,spot_nameカラムを代入
  def address
    [self.prefecture_i18n, self.place].compact.join()
  end
  # 送信されたaddressの値によってジオコーディング(緯度経度の算出)を行う
  geocoded_by :address
  after_validation :geocode, if: :prefecture||:place_changed?

  # 都道府県
  enum prefecture: {
     北海道:1,青森県:2,岩手県:3,宮城県:4,秋田県:5,山形県:6,福島県:7,
     茨城県:8,栃木県:9,群馬県:10,埼玉県:11,千葉県:12,東京都:13,神奈川県:14,
     新潟県:15,富山県:16,石川県:17,福井県:18,山梨県:19,長野県:20,
     岐阜県:21,静岡県:22,愛知県:23,三重県:24,
     滋賀県:25,京都府:26,大阪府:27,兵庫県:28,奈良県:29,和歌山県:30,
     鳥取県:31,島根県:32,岡山県:33,広島県:34,山口県:35,
     徳島県:36,香川県:37,愛媛県:38,高知県:39,
     福岡県:40,佐賀県:41,長崎県:42,熊本県:43,大分県:44,宮崎県:45,鹿児島県:46,
     沖縄県:47
  }
  
  def self.most_favorite(n = 10)
    where(id: Favorite.group(:post_id).order('count(post_id) desc').limit(n).pluck(:post_id))
  end

  # ransacker :favorites_count do
  # end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  
  # optional: true → nilを許可
  belongs_to :user, optional: true
  belongs_to :post
  
  validates :comment, presence: true, length: {maximum: 200 }

end

app/models/tag.rb
class Tag < ApplicationRecord
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  
  # is_deletedがfalseの時に認証する
  def active_for_authentication?
    super && (is_deleted == false)
  end
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :posts, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  validates :name, presence: true, length: {maximum: 20 }
  
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    @contact = Contact.new
  end
  
  def confirm
    @contact = Contact.new(contact_params)
    if @contact.invalid?
      render 'new'
    end
  end
  
  def back
    @contact = Contact.new(contact_params)
    render 'new'
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      ContactMailer.send_mail(@contact).deliver
      # ContactMailer.send_mail(@contact).deliver_now
      redirect_to complete_contacts_path
    else
      render 'new'
    end
  end
  
  def complete
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :name, :subject, :message)
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def top
    @posts = Post.all
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # deviseのヘルパーメソッド
  before_action :authenticate_user!, only: [:destroy, :destroy_from_user_show]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if user_signed_in?
      # current_user → deviseのヘルパーメソッド
      # ログイン中のユーザー情報を取得
      @post.user_id = current_user.id
    end
    if @post.save
      @post.create_tags
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def index
    # 検索結果をpostsのindexの形式で表示する
    # @posts = Post.allを ↓ に書き換える
    @posts = @search.result.page(params[:page]).reverse_order
    # 検索してない場合は全てのデータが返ってくる
  end

  def show
    @post = Post.find(params[:id])
    @post_comment = PostComment.new
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to posts_path
  end

  def destroy_from_user_show
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to request.referer
  end

  def runking
    @posts = Post.most_favorite
  end

  private

  def post_params
    params.require(:post).permit(:image, :writings, :prefecture, :place, :latitude, :longitude)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # deviseのヘルパーメソッド
  before_action :authenticate_user!,except: [:index, :show]

  def index
    redirect_to new_user_registration_path
  end

  def show
    @user = User.find(params[:id])
    @posts = @user.posts.page(params[:page]).reverse_order
  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
      render 'edit'
    else
      redirect_to user_path(@user.id)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      redirect_to edit_user_path(@user), flash: { error: @user.errors.full_messages }
    end
  end

  # 退会確認画面
  def unsubscribe
    @user = current_user
  end

  # 退会
  def withdraw
    @user = current_user
    if @user.update(is_deleted: true)
      reset_session
      redirect_to root_path
      flash[:withdraw] = "退会しました"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_name(user)
    #ログインしていないユーザーの表示名を設定
    return '街ブラさん' if user.nil?

    path = admin_signed_in? ? "/admin/users/#{user.id}" : "/users/#{user.id}"
    content_tag(:a, href: path) do
      concat user.name
    end
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%#- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%#= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%#= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%#= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<%# end %>

<%#- if devise_mapping.omniauthable? %>
  <%#- resource_class.omniauth_providers.each do |provider| %>
    <%#= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <%# end %>
<%# end %>

app/views/layouts/_error_messages.html.erb
<div class="error_messages">
  <% if model.errors.any? %>
   <%= model.errors.count %>件のエラーが発生しました<br>
   <% model.errors.full_messages.each do |message| %>
     <li><%= message %></li>
    <% end %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <p class="copyright text-center">© 2022 Sao95 inc.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light">
    <!--<div class="container">-->
      <a class="logo" href="/"><%= image_tag('logo.jpg') %></a>
      <!--asset_path(no_image_square.jpg)-->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <div class="navbar-nav ml-auto ">
        <!--<%# if user_signed_in? %> → devise側で用意しているヘルパー-->
        <% if admin_signed_in? %>
          <span class="btn"><%= link_to "会員一覧", admin_users_path %></span>
          <span class="btn"><%= link_to "投稿一覧", admin_posts_path %></span>
          <span class="btn"><%= link_to "コメント一覧", admin_post_comments_path %></span>
          <span class="btn"><%= link_to "ログアウト", destroy_admin_session_path, method: :delete %></span>
        <% elsif user_signed_in? %>
          <span class="btn"><%= link_to "Home", root_path %></span>
          <span class="btn"><%= link_to "マイページ", user_path(current_user) %></span>
          <span class="btn"><%= link_to "投稿一覧", posts_path %></span>
          <!--method: :deleteでdestroy_user_session_pathへルーティングさせる-->
          <span class="btn"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></span>
        <% else %>
          <span class="btn"><%= link_to "Home", root_path %></span>
          <span class="btn"><%= link_to "投稿一覧", posts_path %></span>
          <span class="btn"><%= link_to "新規登録", new_user_registration_path %></span>
          <span class="btn"><%= link_to "ログイン", new_user_session_path %></span>
        <% end %>
        </div>
      </div>
    <!--</div>-->
  </nav>
  <!--フラッシュメッセージ-->
  <div id="application_flash_message"><p><%= flash[:withdraw] %></p></div>
  <div id="application_flash_message"><p><%= flash[:success] %></p></div>
</header>

app/views/layouts/_pagetop.html.erb
<!--トップへ戻るボタン-->
<span id="pagetop">
  <a href="#">
    <!--ボタンの表示にはFontAwesomeを使用-->
     <i class="fas fa-chevron-up"></i>
  </a>
</span>

app/views/layouts/_sidebar.html.erb
<% if admin_signed_in? %>
<% else %>
  <div class="search">
    <!--search_form_for → ransackが提供するフォームヘルパー-->
    <%= search_form_for @search do |f| %>
      <%#= f.label :address_or_writings_or_user_name_cont, "Keyword" %>
      <%= f.search_field :prefecture_or_place_or_writings_or_user_name_cont, class: 'form-control', placeholder: '検索ワード', required: true %>
      <!--<div class='prefecture_search'>-->
      <!--  <%#= f.select :prefecture_eq, Post.prefectures_i18n.invert.map{|key, value| [key, Post.prefectures[value]]}, { include_blank: t('都道府県') }, { class: 'form-control' } %>-->
      <!--</div>-->
      <%= f.submit '検索', class: 'btn' %>
    <% end %>
    
  </div>
  
  <div class="row link_btn1">
    <%= link_to new_post_path do %>
    <table class='btn'>
      <td class='col-2'><i class="fas fa-pen"></i></td>
      <td class='col-10'><p>投稿フォーム</p></td>
    </table>
    <% end %>
    
    <%= link_to new_contact_path do %>
    <table class='btn'>
      <td class='col-2'><i class="far fa-bell"></i></td>
      <td class='col-10'><p>お問い合わせ</p></td>
    </table>
    <% end %>
    
    <%= link_to runking_posts_path do %>
    <table class='btn'>
      <td class='col-2'><i class="fas fa-award"></i></td>
      <td class='col-10'><p>ランキング</p></td>
    </table>
    <% end %>
  </div>
 <% end %>
 
<!--<div class="row link_btn2">-->
<!--  <%# if user_signed_in? %>-->
    <!--@userはapplicationコントローラーでcurrent_userに設定している-->
<!--    <%#= link_to user_post_comments_path(@user) do %>-->
<!--    <table class='btn'>-->
<!--      <td class='col-2'><span></span></td>-->
<!--      <td class='col-10'><p>コメント履歴一覧</p></td>-->
<!--    </table>-->
<!--    <%# end %>-->
<!--    <%#= link_to user_favorites_path(@user) do %>-->
<!--    <table class='btn'>-->
<!--      <td class='col-2'><span></span></td>-->
<!--      <td class='col-10'><p>お気に入り履歴一覧</p></td>-->
<!--    </table>-->
<!--    <%# end %>-->
<!--  <%# end %>-->
<!--</div>-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Machibura</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">-->
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/bxslider/4.2.12/jquery.bxslider.min.js"></script>
  </head>

  <body>
    <div id="wrapper">
      <%= render "layouts/header" %>
      <main>
        <div class="container-fluid">
          <div class="row, application_row">
            <% if admin_signed_in? %>
              <div class="admin_main_content">
                <%= yield %>
              </div>
            <% else %>
              <div class="col-md-3 sidebar">
                <%= render "layouts/sidebar" %>
              </div>
              <div class="col-md-9 main_content">
                <%= yield %>
              </div>
            <% end %>
          </div>
        </div>
      <%= render "layouts/pagetop" %>
      </main>
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>